version: "3"

services:
    my_ubuntu_work:
        container_name: my_ubuntu_work
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USER_NAME=alick
                - USER_GROUP=alick
                - USER_PASSWORD=1
                - UBUNTU_VERSION=20.04
                - UBUNTU_MIRROR=http://mirrors.163.com/ubuntu/

        image: my_ubuntu:v1
        volumes:
            - data_volume:/home/alick
        ports:
            - "8022:22"
        network_mode: "bridge"
volumes:
    data_volume:
        external:
            name: my_ubuntu_workspace_data_volume
