version: "3"

services:
    my_ubuntu_work:
        container_name: my-ubuntu-work
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - USER_NAME=alick
                - USER_GROUP=alick
                - USER_PASSWORD=1
                - UBUNTU_VERSION=22.04
                - UBUNTU_MIRROR=http://mirrors.163.com/ubuntu/

        image: my_ubuntu:1.0.2
        volumes:
            - my_ubuntu_workspace_data_volume:/home/alick
        ports:
            - "8022:22"
        network_mode: "bridge"
volumes:
    my_ubuntu_workspace_data_volume:
        external: true
