test:test.c
	@gcc -o test test.c
#p_sleep:p_sleep.c
	@gcc -o p_sleep p_sleep.c
#proc_sleep:proc_sleep.c
	@gcc -o proc_sleep proc_sleep.c
.PHONY:clean
clean:
	@rm -f test
	@rm -f p_sleep
	@rm -f proc_sleep
