version: '3'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 61613:61613
    volumes:
      - ./rabbitmq-log:/var/log/rabbitmq
      - ./rabbitmq-data:/var/lib/rabbitmq
      - ./rabbitmq-config:/etc/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_PLUGINS=rabbitmq_management rabbitmq_stomp

